name: The Giraffe Project
favicon: null
layout_spectrum: 0.12401
typography_spectrum: 0.28315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#101211'
    - '#a79877'
    - '#264033'
    - '#fba200'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
