name: The Giraffe Project
favicon: null
layout_spectrum: 0.12401
typography_spectrum: 0.13857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121215'
    - '#ecb550'
    - '#9e4a2a'
    - '#f3e1b0'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.9147612049710006
  rhythmicContrast: 0.5
purpose: []
