name: The Giraffe Project
favicon: null
layout_spectrum: 0.12401
typography_spectrum: 0.28315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#535641'
    - '#ffffff'
    - '#881a1d'
    - '#fcb482'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
