name: The Giraffe Project
favicon: null
layout_spectrum: 0.3305
typography_spectrum: 0.28315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edefff'
    - '#585c45'
    - '#222126'
    - '#c2c3f1'
    - '#908ebd'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
