name: The Giraffe Project
favicon: null
layout_spectrum: 0.17896
typography_spectrum: 0.28315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf3fb'
    - '#69b3fb'
    - '#8f590f'
    - '#e5aa21'
    - '#291f16'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
