name: The Giraffe Project
favicon: null
layout_spectrum: 0.3305
typography_spectrum: 0.28315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edebf6'
    - '#251c17'
    - '#4a723e'
    - '#7d6a7d'
    - '#9bb288'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
